version: "3.9"

services:
  db:
    image: postgres:14
    container_name: app_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: app_redis
    ports:
      - "6379:6379"
volumes:
  dbdata:
