name: build-images
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # para publicar en GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Set vars
        id: vars
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "REPO=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # API
      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.OWNER }}/${{ steps.vars.outputs.REPO }}/api:latest
            ghcr.io/${{ steps.vars.outputs.OWNER }}/${{ steps.vars.outputs.REPO }}/api:${{ steps.vars.outputs.SHA }}

      # ETL
      - name: Build & push ETL
        uses: docker/build-push-action@v6
        with:
          context: ./etl
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.OWNER }}/${{ steps.vars.outputs.REPO }}/etl:latest
            ghcr.io/${{ steps.vars.outputs.OWNER }}/${{ steps.vars.outputs.REPO }}/etl:${{ steps.vars.outputs.SHA }}

      - name: Make packages public (optional si tu repo es público)
        run: |
          echo "Haz las imágenes públicas desde la UI de GitHub → Packages, si no quedan visibles."
